name: clean_arch
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.5
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  test: ^1.22.0
  faker: ^2.1.0
  mocktail: ^0.3.0


flutter:
  uses-material-design: true

  assets:
    - lib/ui/assets/

flutter_icons:
  ios: true
  android: true
  image_path_ios: lib/ui/assets/icon/ios.png
  image_path_android: lib/ui/assets/icon/android.png
  adaptive_icon_background: lib/ui/assets/icon/background.png
  adaptive_icon_foreground: lib/ui/assets/icon/foreground.png